/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comboboxexample;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author janderson.c
 */
public class jfMain extends javax.swing.JFrame {

    /**
     * Creates new form jfMain
     */
    public jfMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbCountry = new javax.swing.JComboBox<>();
        jlbCountry = new javax.swing.JLabel();
        jbtShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jcbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlbCountry.setText("Country:");

        jbtShow.setText("Show");
        jbtShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jlbCountry)
                .addGap(18, 18, 18)
                .addComponent(jcbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtShow)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCountry)
                    .addComponent(jbtShow))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Create ArrayList of Countries
        List<Country> listCountry = new ArrayList<>(); 
        
        //Clear combobox and arraylist
        jcbCountry.removeAllItems();
        listCountry.clear();
        
        // Create new instance of the class 
        // and set values
        Country objCountry = new Country();
        objCountry.setIdCountry(0);
        objCountry.setCountry("Select a country");                
        listCountry.add(objCountry);
        
        objCountry = new Country();
        objCountry.setIdCountry(1);
        objCountry.setCountry("Brazil");                
        listCountry.add(objCountry);
        
        objCountry = new Country();
        objCountry.setIdCountry(2);
        objCountry.setCountry("Germany");
        listCountry.add(objCountry);
                
        objCountry = new Country();
        objCountry.setIdCountry(3);
        objCountry.setCountry("United States");
        listCountry.add(objCountry);
        
        
        jcbCountry.setModel(new DefaultComboBoxModel(listCountry.toArray()));
    }//GEN-LAST:event_formWindowOpened

    private void jbtShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtShowActionPerformed
        //Create obj with data of selected item combobox. 
        Country objCountry =  (Country) jcbCountry.getSelectedItem();
        
        if(objCountry.getIdCountry() > 0) {
            //Show description of country
            JOptionPane.showMessageDialog(null,"Key: "+ objCountry.getIdCountry() 
                                             + "\nDescription: " + objCountry.getCountry());    
        } else {
            JOptionPane.showMessageDialog(null,"Need to fill in the combobox");    
        }
        
    }//GEN-LAST:event_jbtShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtShow;
    private javax.swing.JComboBox<String> jcbCountry;
    private javax.swing.JLabel jlbCountry;
    // End of variables declaration//GEN-END:variables
}
